# Generated by Django 5.0.4 on 2024-04-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('id_item', models.IntegerField()),
                ('count', models.IntegerField(max_length=12)),
                ('cost', models.FloatField(max_length=12)),
                ('summary', models.FloatField(max_length=20)),
            ],
            options={
                'ordering': ['id_user'],
            },
        ),
        migrations.CreateModel(
            name='Item_Shop',
            fields=[
                ('id_item', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40, unique=True)),
                ('cost', models.FloatField(max_length=12)),
                ('info', models.CharField(max_length=250)),
                ('ico', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id_item'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=600)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('login', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['id_user'],
            },
        ),
    ]
