# Generated by Django 5.0.4 on 2024-04-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='count',
            field=models.IntegerField(),
        ),
    ]
