# Generated by Django 5.0.4 on 2024-04-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_carts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_shop',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='Url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=53, max_length=255, unique=True, verbose_name='Url'),
            preserve_default=False,
        ),
    ]
