# Generated by Django 5.0.4 on 2024-04-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_shop_slug_news_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item_Shop',
            new_name='ItemShop',
        ),
    ]
