# Generated by Django 5.0.4 on 2024-04-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_carts_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='title',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
